#!/usr/bin/env python

import roslib
roslib.load_manifest('urdfpy')
import rospy

import sys

from urdfpy import *

robot = None

def usage():
    print("display_urdf <urdf file>")
    print("\tLoad an URDF file.")
    print("display_urdf")
    print("\tDisplay the parameter server current robot description.")
    sys.exit(1)

if len(sys.argv) > 2:
    usage()
if len(sys.argv) == 2 and (sys.argv[1] == "-h" or sys.argv[1] == "--help"):
    usage()

if (len(sys.argv) == 1):
    robot = parseFromParameterServer()
else:
    robot = parse(sys.argv[1])
print(robot)
